swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "filter"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /filter/sendData:
    post:
      tags:
      - "filter"
      summary: "Посылает в сервис notify данные для уведомлений. "
      description: "Посылает в сервис notify данные для уведомлений. "
      operationId: "sendData"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Посылает в сервис notify данные для уведомлений. "
        required: true
        schema:
          $ref: "#/definitions/Filter"
      responses:
        default:
          description: "завершено успешно"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Filter:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      currency:
        type: "string"
      value:
        type: "integer"
        format: "int64"
      event:
        type: "string"
    xml:
      name: "User"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"