services:
  influxdb:
    image: influxdb:latest
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 3s
      timeout: 10s
      retries: 5
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb2
    env_file: .env

  observersdb:
    volumes:
      -
      #я не знаю что тут писать

  usersdb:
    #страшно вырубай

  storage:
    build: storage
    depends_on:
      influxdb:
        condition: service_healthy
    env_file: .env
    ports:
      - 81:81

  filter:
    build: filter
    env_file: .env
    ports:
      - 82:82

  notify:
    build: notify
    env_file: .env
    ports:
      - 83:83

  fetcher:
    build: fetcher
    env_file: .env
    ports:
      - 84:84

  users:
    build: users
    env_file: .env
    ports:
      - 85:85

volumes:
  influxdb:
  filter_db:
  users_db: