services:
  influxdb:
    image: influxdb:latest
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 3s
      timeout: 10s
      retries: 5
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb2
    env_file: .env

  storage:
    build: storage
    depends_on:
      influxdb:
        condition: service_healthy
    env_file: .env
    ports:
      - 81:80

  filter:
    build: filter
    env_file: .env
    volumes:
      - filter_db:/var/www/app/database
    ports:
      - 82:80

  notifier:
    build: notifier
    env_file: .env
    ports:
      - 83:80

  fetcher:
    build: fetcher
    env_file: .env
    ports:
      - 84:80

  users:
    build: users
    env_file: .env
    volumes:
      - filter_db:/var/www/app/database
    ports:
      - 85:80

volumes:
  influxdb:
  filter_db:
  users_db: