openapi: 3.0.0
info:
  title: Notifier
  description: Сервис уведомлений.
  version: 0.0.1
servers:
  - url: http://notifier/v1
paths:
  /user:
    post:
      summary: Создать пользователя
      description: Создание нового пользователя
      
      requestBody:
        description: "Пользователь"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        201:
          description: Пользователь создан
        403:
          description: Не удалось создать пользователя
  
  /user/{id}:
    get:
      summary: Получение данных пользователя.
      description: Получение подробной информации о пользователе по его идентификатору.
      parameters:
        - name: id
          in: "path"
          description: "ID пользователя"
          required: true
          schema:
            type: integer
            format: int64
            description: ID пользователя
      responses:
        "200":
          description: Данные о пользователе получены
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: Пользователь не найден
  /login:
    post:
      summary: "Вход в систему"
      description: "Аутентификация пользователя"
      requestBody:
        description: "Учетные данные пользователя"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Логин
                password:
                  type: string
                  description: Пароль
      responses:
        "200":
          description: Пользователь аутентифицирован
          content:
            application/json:
              schema:
                type: integer
                description: ID пользователя
        "400":
          description: Неправильный логин или пароль

components:
  schemas:
    User:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        username:
          type: "string"
        firstName:
          type: "string"
        lastName:
          type: "string"
        email:
          type: "string"
        password:
          type: "string"